import type { Metadata } from "next";
import { Rubik, Pacifico } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/layout";
// import ReduxProvider from "@/lib/store/redux-provider";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  variable: "--font-pacifico",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ReduxProvider>
    <html lang="en">
      <body className={`${rubik.variable} ${pacifico.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
    // </ReduxProvider>
  );
}
